kind: Card
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: throughput-card
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    title: Compositions created
    variant: outlined
    headerLeft: 'per day · last 14 days'
    items:
    - resourceRefId: throughput-chart
  resourcesRefs:
    items:
    - id: throughput-chart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: throughput-chart
      namespace: {{ .Release.Namespace }}
      resource: linecharts
      verb: GET
