kind: Flex
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: header-greeting-flex
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    allowedResources:
    - paragraphs
    vertical: true
    items:
    - resourceRefId: greeting-eyebrow
    - resourceRefId: greeting-title
    - resourceRefId: greeting-subtitle
  resourcesRefs:
    items:
    - id: greeting-eyebrow
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: greeting-eyebrow
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET
    - id: greeting-title
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: greeting-title
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET
    - id: greeting-subtitle
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: greeting-subtitle
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET
