kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: delta-cap-compositions
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    text: new this week
    type: secondary
  widgetDataTemplate:
  - forPath: text
    expression: >-
      ${ {"24h":"new in the last 24 hours","7d":"new this week","30d":"new this month","all":"new (all time)"}[.range // "all"] }
  apiRef:
    name: dashboard-data
    namespace: {{ .Release.Namespace }}
  resourcesRefs:
    items: []
