kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-subtitle
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    text: Provisioned platform resources across your clusters
    type: secondary
  resourcesRefs:
    items: []
