apiVersion: widgets.templates.krateo.io/v1beta1
kind: PieChart
metadata:
  name: braghettos-repo-topics-pie
  namespace: krateo-system
spec:
  apiRef:
    name: braghettos-krateo-repos
    namespace: krateo-system
  widgetData:
    title: Repos by Topic
    angleField: count
    colorField: topic
    data: []
  resourcesRefs:
    items: []
  widgetDataTemplate:
    - forPath: data
      expression: '${ .items | map(.topics) | flatten | group_by(.) | map({ topic: .[0], count: length }) }'
