apiVersion: widgets.templates.krateo.io/v1beta1
kind: PieChart
metadata:
  name: braghettos-repo-explorer-topics-pie
  namespace: krateo-system
spec:
  apiRef:
    name: braghettos-repo-explorer
    namespace: krateo-system
  widgetData:
    angleField: count
    colorField: topic
    data: []
  resourcesRefs:
    items: []
  widgetDataTemplate:
    - forPath: data
      expression: '${ [ .items[] | .topics[] ] | group_by(.) | map({ topic: .[0], count: length }) }'
