kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: charts-row
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    allowedResources:
    - cards
    alignment: stretch
    items:
    - resourceRefId: throughput-card
      size: 16
    - resourceRefId: status-card
      size: 8
  resourcesRefs:
    items:
    - id: throughput-card
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: throughput-card
      namespace: {{ .Release.Namespace }}
      resource: cards
      verb: GET
    - id: status-card
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: status-card
      namespace: {{ .Release.Namespace }}
      resource: cards
      verb: GET
