kind: Tag
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: delta-tag-failed
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    label: 0%
    color: red
    style:
      fontSize: '22px'
      fontWeight: 700
      lineHeight: '26px'
  widgetDataTemplate:
  - forPath: label
    expression: '${ (if (.list|length)>0 then ((([.list[]|select((.conditions//[])|any(.type=="Ready" and .status=="False"))]|length)*100/(.list|length))|floor) else 0 end | tostring) + "%" }'
  apiRef:
    name: compositions-list
    namespace: {{ .Release.Namespace }}
  resourcesRefs:
    items: []
