kind: Tag
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: delta-tag-compositions
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    label: '+0'
    color: blue
  widgetDataTemplate:
  - forPath: label
    expression: '${ "+" + (([.list[]|select(((.ts//"")|length>0) and ((.ts|fromdate) > (now-604800)))]|length)|tostring) }'
  apiRef:
    name: compositions-list
    namespace: {{ .Release.Namespace }}
  resourcesRefs:
    items: []
