kind: Flex
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: page-builderdemo
  namespace: krateo-system
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    allowedResources:
    - paragraphs
    vertical: true
    gap: middle
    items:
    - resourceRefId: builderdemo-title
    - resourceRefId: builderdemo-note
  resourcesRefs:
    items:
    - id: builderdemo-title
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: builderdemo-title
      namespace: krateo-system
      resource: paragraphs
      verb: GET
    - id: builderdemo-note
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: builderdemo-note
      namespace: krateo-system
      resource: paragraphs
      verb: GET
