kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: alerts-title
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    text: Alerts
    strong: true
  resourcesRefs:
    items: []
