kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: stats-row
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    allowedResources:
    - cards
    items:
    - resourceRefId: stat-card-compositions
      size: 6
    - resourceRefId: stat-card-healthy
      size: 6
    - resourceRefId: stat-card-reconciles
      size: 6
    - resourceRefId: stat-card-failed
      size: 6
  resourcesRefs:
    items:
    - id: stat-card-compositions
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: stat-card-compositions
      namespace: {{ .Release.Namespace }}
      resource: cards
      verb: GET
    - id: stat-card-healthy
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: stat-card-healthy
      namespace: {{ .Release.Namespace }}
      resource: cards
      verb: GET
    - id: stat-card-reconciles
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: stat-card-reconciles
      namespace: {{ .Release.Namespace }}
      resource: cards
      verb: GET
    - id: stat-card-failed
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: stat-card-failed
      namespace: {{ .Release.Namespace }}
      resource: cards
      verb: GET
